type Patient {
    id: ID!
    name: String!
    cpf: String!
    email: String!
}

type Doctor {
    id: ID!
    name: String!
    crm: String!
    specialty: String!
}

type Appointment {
    id: ID!
    patient: Patient!
    doctor: Doctor!
    dateTime: String!
    status: AppointmentStatus!
}

enum AppointmentStatus {
    SCHEDULED
    COMPLETED
    CANCELED
}

type Query {
    appointmentsByPatient(patientId: ID!): [Appointment!]!

    futureAppointmentsByPatient(patientId: ID!): [Appointment!]!

    appointmentHistory(patientId: ID!): [Appointment!]!

    appointment(id: ID!): Appointment!
}

type Mutation {
    createAppointment(
        patientId: ID!
        doctorId: ID!
        dateTime: String!
    ): Appointment!

    cancelAppointment(
        id: ID!
    ): Appointment!

    completeAppointment(
        id: ID!
    ): Appointment!
}